version: "3.9"

services:
  api1:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api-test
    command: node app.js
    ports:
      - 4000:4000